//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemanaAcademica.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public Local()
        {
            this.Horario = new HashSet<Horario>();
        }
    
        public int id_local { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
