
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SemanaAcademica.Models.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TrabalhoVoluntario
{

    public int id_trabalho { get; set; }

    public int horas { get; set; }

    public int id_participante { get; set; }

    public System.DateTime data_inicio { get; set; }

    public System.DateTime data_fim { get; set; }



    public virtual Participante Participante { get; set; }

}

}
